/* 新西兰南岛 13 天 · 行程数据（源自 v3 路书，离线内置，无需联网） */

const TRIP = {
  meta: {
    title: "新西兰南岛 13 天",
    subtitle: "2026.9.24 香港出发 — 10.7 返抵香港",
    crew: "8 人 · 2 台 7 座四驱 · 5 处民宿",
    depIso: "2026-09-24",
    dstNote: "9/27 周日 02:00 时钟跳到 03:00（夏令时开始），中纽时差 4h → 5h，手表和闹钟要手动调。",
  },

  /* 出发前必看 · 十条 */
  topTen: [
    { n: 1, level: "high", title: "库克山 Heli-Hike 免费取消 9/24 截止", detail: "8 人共 ¥26,800（¥3,350/人）。不去的人必须今天退，过了 9/24 退不了。" },
    { n: 2, level: "high", title: "NZTD 入境申报：1、2、4 队仍「未完成」", detail: "登机前 24 小时内才能提交，全队都要做。" },
    { n: 3, level: "high", title: "米尔福德集合点是 The Rees Hotel 对面的公交站，不是机场", detail: "10/3 接送 09:15 起，09:05 前到位；08:30 先打 +64 3 249 6000 / 0800 65 65 01 确认天气。" },
    { n: 4, level: "mid", title: "观鲸地址是 Peketa 的 Air Kaikoura Aero Club（627 SH1）", detail: "不是 Kaikoura Airport，更不是码头。3 人班 08:30 签到，5 人班 09:30 签到。" },
    { n: 5, level: "mid", title: "9/27 周日凌晨 2:00 时钟跳到 3:00", detail: "夏令时开始，中纽时差 4h → 5h，手表闹钟要手动调。" },
    { n: 6, level: "mid", title: "10/1 观星别早到", detail: "确认函明写「开团前 5–10 分钟到即可，早到车灯会严重影响上一团」。00:50 到 70 Andrew Don Drive，且必须用 Google Maps。" },
    { n: 7, level: "mid", title: "瓦纳卡射击是 Crossfire Shooting 13:45", detail: "不是表里的 Real Guns 14:00。地址 9 Mt Barker Road（机场对面），13:30 签到。" },
    { n: 8, level: "high", title: "10/5 跳伞 08:15 签到、约 12:00 才结束", detail: "12:30 才发车去奥马鲁；若跳伞顺延，宁可放弃跳伞也别误 19:30 的企鹅。" },
    { n: 9, level: "mid", title: "10/4 滑翔伞只有 11:00 场次一份确认函（2 人）", detail: "表里还写了 10:00 场次 4 人，务必核实那份确认函。" },
    { n: 10, level: "high", title: "禁行路段不是「不能开」，是保险不赔", detail: "开进去不违法，但出事故车损险与第三者险全部失效，拖车费动辄 NZ$1,000 起。" },
  ],

  /* 机票（确认函核对版） */
  flights: [
    { dir: "去程 · 2 段", date: "9/24 20:05", text: "QF030 香港 T1 → 墨尔本 T2（9/25 07:20）→ QF5563 / 捷星 JQ171 → 基督城（9/25 16:25）", note: "中转 3h45m · ⚠️ 行李不直挂，墨尔本需提取行李重新托运 · ¥6,694/人" },
    { dir: "回程 · 2 段", date: "10/7 06:20", text: "QF168 基督城 → 墨尔本 T2（08:10）→ QF029 → 香港 T1（17:55）", note: "中转 3h05m · ✅ 行李直挂，中转不用取行李" },
  ],

  /* 航班信息（按确认函逐段核对） */
  flightInfo: {
    outbound: {
      title: "🛫 去程 · 香港 → 基督城（9/24–9/25）",
      bagOk: false,
      transfer: "墨尔本机场 T2 · 3 小时 45 分钟（07:20 落地 → 11:05 起飞）",
      baggage: "⚠️ 行李不直挂（Baggage not checked through）——必须在墨尔本自己提取行李、重新托运",
      segments: [
        {
          seg: "香港 → 墨尔本", flight: "QF030",
          dep: "9/24 周四 20:05", depAirport: "香港国际机场 T1（HKG）",
          arr: "9/25 周五 07:20", arrAirport: "墨尔本机场 T2（MEL）",
          airline: "澳洲航空 Qantas Airways QF030",
        },
        {
          seg: "墨尔本 → 基督城", flight: "QF5563 / JQ171",
          dep: "9/25 周五 11:05", depAirport: "墨尔本机场 T2（MEL）",
          arr: "9/25 周五 16:25", arrAirport: "克赖斯特彻奇国际机场（CHC）",
          airline: "澳洲航空 QF5563 · 捷星航空 JQ171（代码共享）",
        },
      ],
    },
    return: {
      title: "🛬 回程 · 基督城 → 香港（10/7）",
      bagOk: true,
      transfer: "墨尔本机场 T2 · 3 小时 5 分钟（08:10 落地 → 11:15 起飞）",
      baggage: "✅ 行李直挂（Baggage checked through）——基督城直接挂到香港，中转不用取行李",
      segments: [
        {
          seg: "基督城 → 墨尔本", flight: "QF168",
          dep: "10/7 周三 06:20", depAirport: "克赖斯特彻奇国际机场（CHC）",
          arr: "10/7 周三 08:10", arrAirport: "墨尔本机场 T2（MEL）",
          airline: "澳洲航空 Qantas Airways QF168",
        },
        {
          seg: "墨尔本 → 香港", flight: "QF029",
          dep: "10/7 周三 11:15", depAirport: "墨尔本机场 T2（MEL）",
          arr: "10/7 周三 17:55", arrAirport: "香港国际机场 T1（HKG）",
          airline: "澳洲航空 Qantas Airways QF029",
        },
      ],
    },
    transferTips: [
      "行李不直挂 = 落地墨尔本后，先跟「Baggage / 行李」指示牌到转盘提取全部行李",
      "过境澳洲：走转机通道，澳洲过境签 771 批准信纸质件随身备查",
      "提取行李后到国内出发层（QF5563 实际由捷星 JQ171 执飞）重新办理托运",
      "国内段托运一般提前 45–60 分钟截止，3h45m 够用但别磨蹭，优先办托运再逛",
    ],
  },

  /* 逐日行程 */
  days: [
    {
      id: 1, iso: "2026-09-24", date: "9/24", weekday: "周四",
      title: "香港 → 墨尔本 → 基督城（跨日）", stay: "机上",
      items: [
        { time: "20:05", tag: "flight", title: "QF030 香港起飞（T1）→ 墨尔本 T2",
          notes: ["提前 3 小时到机场（建议 17:00 前到 T1）", "9/25 07:20 落地墨尔本 T2",
                  "重要：墨尔本中转「行李不直挂」，必须自己取行李重新托运",
                  "澳洲过境签 771 批准信必查，纸质件随身", "第二段 9/25 11:05 QF5563 / 捷星 JQ171（代码共享）→ 基督城 16:25"] },
      ],
    },
    {
      id: 2, iso: "2026-09-25", date: "9/25", weekday: "周五 · 中秋",
      title: "16:25 落地 → 提车 → 入住 → 中秋晚餐", stay: "基督城",
      items: [
        { time: "16:25", tag: "p0", title: "基督城机场（CHC）落地",
          notes: ["入境流程：NZTD 申报扫码 → 生物安全检查（鞋底泥土）→ 取行李", "全队一起走，约 50–70 分钟"] },
        { time: "17:40", tag: "p0", title: "机场提车（2 台）",
          notes: ["三菱帕杰罗运动版或同组，自动挡 / 7 座 / 四驱", "提车单号：Rental Voucher 1008979697 与 1008979737（车辆1.pdf / 车辆2.pdf）",
                  "必带：中国驾照原件 + 官方翻译件、芯片国际信用卡（主驾驶人名下）、提车单",
                  "现场必须登记副驾驶人（默认只含 1 人，不登记的人开车出事全责自付）",
                  "取车时绕车拍视频，重点拍前后杠、轮毂、玻璃、车顶"] },
        { time: "18:30", tag: "stay", title: "抵达民宿 · 放行李", addr: "198 Chester Street East, Christchurch Central City 8011",
          notes: ["机场 → 市区约 20–25min", "实际是两套公寓、行李要搬上二楼、只能停马路车位——行李精简到能一次拎上楼"] },
        { time: "19:15", tag: "meal", title: "已订 · 中秋节晚餐 Fiddlesticks Restaurant",
          notes: ["预订人名字是 Robert，确认邮件在 gmail 邮箱，务必提前翻出来",
                  "全程最赶的一段：落地 16:25 + 入境 1h + 提车 40min，19:15 到餐厅几乎没有余量",
                  "建议：先让 1 位不提车的人打车直奔餐厅，赶不上就现场改到 19:45／20:00"] },
        { time: "21:00", tag: "p1", title: "采购 PAK'nSAVE Moorhouse（营业到 22:00）",
          notes: ["买：凯库拉当天往返的水和零食、晕机药（若没带）、三天早餐食材、便当材料", "9/26 晚上还要再来一次做便当"] },
      ],
    },
    {
      id: 3, iso: "2026-09-26", date: "9/26", weekday: "周六",
      title: "农夫市集 + 赏樱 + Gondola + 市区", stay: "基督城",
      items: [
        { time: "09:00", tag: "meal", title: "Christchurch Farmers' Market（周六限定 9:00–12:00）",
          notes: ["只有周六上午有，今天是唯一机会", "United Fisheries Ltd 早上有鳌虾，下午就没了——想吃鳌虾要早去", "顺路去坎特伯雷大学"] },
        { time: "10:00", tag: "p1", title: "赏樱 · 坎特伯雷大学 Ilam Gardens",
          notes: ["市区自驾约 10min+，主校区 Ilam Gardens 周围、靠近校园河畔的区域有晚樱",
                  "备选：海格力公园（市中心植物园旁，8min，有专门樱花小道，公园北部停车）",
                  "备选：Halswell Quarry Park（南郊 20min+，有山有水位足）"] },
        { time: "12:00", tag: "meal", title: "午餐 · Little High Eatery 或 Riverside Market",
          notes: ["两家都是美食广场，人多时好分流"] },
        { time: "13:45", tag: "p1", title: "Christchurch Gondola 缆车观景",
          notes: ["市区 → 缆车站约 20–30min（在 Heathcote Valley，东南向，和上午在西边的行程是两个方向）",
                  "晴天优先，低云／大风时价值大幅下降——早上看天气，不好就和下午的植物园对调", "现场买票，和小火车有套票"] },
        { time: "16:15", tag: "p1", title: "植物园 + Arts Centre 城市散步",
          notes: ["市区内 5–15min，1.5–2h，免费", "可加复古小火车（日卡，随上随下），时间紧可压缩"] },
        { time: "18:30", tag: "meal", title: "PAK'nSAVE Moorhouse 买菜 → 回家做饭",
          notes: ["今晚要做好 9/27 的便当（次日早餐不吃或用便当，坐小飞机可能吐，建议清淡）", "超市 22:00 关门"] },
        { time: "20:00", tag: "tip", title: "整理行李 + 确认次日观鲸",
          notes: ["确认两批确认函都能离线打开", "记下 +64 3 319 6579（次日出发前要打）"] },
      ],
    },
    {
      id: 4, iso: "2026-09-27", date: "9/27", weekday: "周日 · 夏令时开始",
      title: "凯库拉固定翼观鲸 + 半岛步道", stay: "基督城",
      items: [
        { time: "02:00", tag: "alert", title: "时钟自动跳到 03:00",
          notes: ["手机会自动跳，但手表和闹钟要手动调", "中纽时差从 4h 变成 5h", "今天所有「墙钟时间」都按跳表后算"] },
        { time: "04:15", tag: "call", title: "致电 +64 3 319 6579 确认能否飞行", tel: "+64 3 319 6579",
          notes: ["确认函原文：建议提前 1 小时或出发前致电，确认天气是否能正常飞行、是否满足最小成行人数", "按 05:15 出发倒推，04:15 打正好"] },
        { time: "05:15", tag: "drive", title: "出发去凯库拉",
          notes: ["基督城 → Peketa（Kaikōura 以南）180km / 约 2.5h", "早餐不吃或吃便当，清淡", "晕机药提前 30–60 分钟吃（4 队记得带）"] },
        { time: "07:45", tag: "p0", title: "抵达 Air Kaikoura Aero Club", addr: "627 State Highway 1, Peketa, Kaikōura 7374", tel: "+64 3 319 6579",
          notes: ["不是 Kaikoura Airport、更不是码头——旧表写「出海观鲸」容易开错地方", "Peketa 在镇中心以南约 8km"] },
        { time: "08:00", tag: "p0", title: "第一批签到 → 09:00 起飞（3 人）",
          notes: ["官方要求提前至少 30 分钟办理签到（含安全简报）→ 08:30 前务必到", "飞行 30 分钟，低空绕鲸盘旋，倾斜转弯比想象中晃"] },
        { time: "09:00", tag: "p0", title: "第二批签到 → 10:00 起飞（5 人）",
          notes: ["报道时间 09:30（5 人班确认函已明确）", "机舱窄，只带小腰包 + 相机 + 墨镜，大包上不了机", "迟到按 NO SHOW，不退不改"] },
        { time: "10:40", tag: "p1", title: "两批汇合",
          notes: ["集合地往前开，两队可以错开往前去海角观景"] },
        { time: "11:15", tag: "meal", title: "午餐 · Kaikoura Seafood BBQ Kiosk",
          notes: ["海角附近的 Foodtruck，略贵", "也可回镇上吃"] },
        { time: "12:30", tag: "p1", title: "Kaikoura Peninsula Walkway 海岸步道",
          notes: ["1–2h，免费", "看海岸、海豹栖息地、雪山海景", "与海豹保持距离；海边风大温度低（8–10℃），别穿凉鞋"] },
        { time: "15:00", tag: "drive", title: "返程基督城（180km / 2.5h）",
          notes: ["如果结束得早，可以回来补基督城的 citywalk"] },
        { time: "17:30", tag: "meal", title: "晚餐",
          notes: ["周日晚上基督城大部分餐厅歇业——考虑 Riverside Market 美食广场，或回家做（昨天已采购）", "别指望 walk-in 正餐厅"] },
        { time: "20:00", tag: "tip", title: "打包行李",
          notes: ["明天 9/28 退房去蒂卡波", "蒂卡波民宿 15:00–17:00 前台办理入住，明天要卡这个时间"] },
      ],
    },
    {
      id: 5, iso: "2026-09-28", date: "9/28", weekday: "周一",
      title: "基督城 → Fairlie → 普卡基湖 → 蒂卡波（日落 + 正餐）", stay: "蒂卡波湖",
      items: [
        { time: "09:00", tag: "drive", title: "退房出发（基督城 → 蒂卡波 230km / 3h，中途停 Fairlie）",
          notes: ["早餐民宿简单解决，直奔 Fairlie 小镇吃午餐"] },
        { time: "11:00", tag: "meal", title: "Fairlie Bakehouse（派）",
          notes: ["特色是各种派，鹿肉蔓越莓很特色", "提前两天可以预定派（9/26 前）", "无法预定座位 → 旁边公园野餐或打包车上吃", "热门派店会排队，别拖太久", "旁边 Four Square Fairlie 可补给"] },
        { time: "12:15", tag: "drive", title: "出发 → 普卡基湖（约 90km / 1h）", notes: [] },
        { time: "13:30", tag: "p1", title: "普卡基湖观景 + Mt Cook Alpine Salmon Shop",
          notes: ["蓝湖 + 库克山远景，和 9/29 库克山日顺路重复，今天先看一次", "三文鱼店 17:00 关门，今天先买一份，9/29 若没赶上还能补"] },
        { time: "15:00", tag: "stay", title: "入住 Mt John Homestead（The Cairns Alpine Resort）", addr: "48 Darchiac Drive, Lake Tekapo 7999", tel: "03 6806952",
          notes: ["前台办理入住 15:00–17:00", "17:00 后必须致电 03 6806952 安排「自助入住」（物业经理不住在房源内）", "按 13:30 从普卡基湖出发，15:00 到刚好卡上，别再拖",
                  "客人免费：9 洞高尔夫球场 + 宠物动物园（羊驼、绵羊、奶牛、猪）", "进围栏区喂食需农场人员陪同，时间看 GoTekapo.com"] },
        { time: "16:15", tag: "p1", title: "好牧羊人教堂 + 蒂卡波湖边",
          notes: ["免费，1–1.5h", "夜间拍星不要用强光干扰他人", "Four Square Tekapo（镇上唯一超市，8:00–20:00）顺路买早餐和补给"] },
        { time: "19:44", tag: "p1", title: "日落（19:44–19:55）",
          notes: ["顺序是：先入住 → 教堂湖边看日落 → 再去吃饭，别反过来"] },
        { time: "20:15", tag: "meal", title: "已订 · 晚餐 TLV Restaurant & Bar",
          notes: ["日落 19:55 结束，湖边走到餐厅时间够"] },
      ],
    },
    {
      id: 6, iso: "2026-09-29", date: "9/29", weekday: "周二",
      title: "库克山 Heli-Hike（全程高光）", stay: "蒂卡波湖",
      items: [
        { time: "07:30", tag: "call", title: "致电 0800 650 651 确认飞行状态", tel: "0800 650 651",
          notes: ["确认函原文：Please call 0800 650 651 on the morning of your departure to confirm the flight status",
                  "若取消：① 现场与工作人员商量改期；② 不改期则联系飞猪客服（卷耳猫）核实后全额退款"] },
        { time: "08:00", tag: "tip", title: "出发前加满油",
          notes: ["库克山村里没有加油站（有也极贵）", "蒂卡波或 Twizel 加满"] },
        { time: "08:30", tag: "drive", title: "出发去库克山（100km / 约 1.2–1.5h）",
          notes: ["表里写 1h、注意事项写 1.2–1.5h，按 1.5h 排保险"] },
        { time: "10:15", tag: "p0", title: "抵达 Mt Cook Airport", addr: "Mt Cook Airport, Mount Cook Road, Canterbury 7999", tel: "+64 3 435 1801", notes: [] },
        { time: "10:45", tag: "p0", title: "签到 → 11:00 开始 · 冰川直升机徒步（8 人）",
          notes: ["3–4h，约 15:00 结束", "对方提供：鞋子、外套、冰爪、袜子、登山杖、背包、墨镜（可自带）",
                  "穿：保暖内层 + 防风外层，不要棉质；手套、毛线帽必带", "迟到不退", "出行后找飞猪客服返现 ¥20"] },
        { time: "15:00", tag: "meal", title: "The Old Mountaineers Cafe（镇上快餐）",
          notes: ["冰川下来后如果饿可以在镇上吃，汉堡薯条等快餐", "快吃，别超过 30 分钟"] },
        { time: "15:30", tag: "drive", title: "直接启程回蒂卡波",
          notes: ["今天不做 Hooker Valley Track（2–3h）", "理由：三文鱼店 17:00 关门，需要 16:00 结束库克山才能买到三文鱼", "Hooker Valley 作为直升机因天气取消时的替补"] },
        { time: "16:20", tag: "p1", title: "Mt Cook Alpine Salmon Shop",
          notes: ["回程顺路（普卡基湖畔 SH80 路口）", "买到就今晚做；没买到的话 10/1 还有机会或直接在镇上吃别的"] },
        { time: "17:30", tag: "p1", title: "普卡基湖观景（0.5–1h）",
          notes: ["蓝湖 + 库克山远景", "若体力还行可改走 Tasman Glacier View / Blue Lakes Walk（0.75–1.5h，有台阶、注意防滑）"] },
        { time: "19:00", tag: "meal", title: "回蒂卡波 · 自己做 / 镇上吃",
          notes: ["买到三文鱼就回家做；没买到就 Four Square 补货自己整，或镇上吃别的"] },
      ],
    },
    {
      id: 7, iso: "2026-09-30", date: "9/30", weekday: "周三",
      title: "缓冲日 · Mt John + 高尔夫 + 蓄力（今晚熬夜观星）", stay: "蒂卡波湖",
      items: [
        { time: "自然醒", tag: "tip", title: "睡到自然醒（补 9/29 疲劳）",
          notes: ["今晚凌晨要观星，白天务必找时间补一觉，不然后天 10/1 转场 + Skyline 会很痛苦"] },
        { time: "10:30", tag: "meal", title: "早餐 · 民宿解决",
          notes: ["上午其他人没起床可以自己先去 Four Square Tekapo 补给"] },
        { time: "11:15", tag: "p1", title: "Mt John 白天观景 / Astro Cafe",
          notes: ["蒂卡波 → Mt John 约 10–15min，1–1.5h", "道路费约 NZ$10/车（带硬币）", "出发前确认道路开放情况", "俯瞰湖区和麦肯齐盆地"] },
        { time: "13:00", tag: "meal", title: "午餐 · Mackenzies Cafe Bar & Grill（walk-in）",
          notes: ["中午这几家都不接受预定，可以在家吃，或者 walk-in", "本地口碑最好的正餐、坎特伯雷羊腿"] },
        { time: "14:30", tag: "p1", title: "自由活动",
          notes: ["民宿客人免费：9 洞高尔夫（借球杆／租球车要提前说）+ 宠物动物园",
                  "Tekapo Springs 温泉（NZD 42–70）：3、4 队已放弃，这是本次全程唯一一次泡温泉的机会，想泡就是今天",
                  "蒂卡波骑马（NZD 120–250）：需现场预约，受天气和马场排期影响"] },
        { time: "18:00", tag: "meal", title: "晚餐 · 自己做（民宿）",
          notes: ["重要更正：Blue Lake Eatery 谷歌显示停业、发邮件确认「确实停业了」", "保底已订 Mackenzies Cafe Bar & Grill 19:15", "若自己做就不去，记得在免费取消时限前取消"] },
        { time: "22:00", tag: "alert", title: "早点睡，为凌晨观星蓄力",
          notes: ["观星集合 00:45、开始 01:00", "早到会严重影响上一团，不要提前去"] },
      ],
    },
    {
      id: 8, iso: "2026-10-01", date: "10/1", weekday: "周四",
      title: "凌晨观星 → 10:30 退房 → 转场皇后镇 → Skyline", stay: "皇后镇",
      items: [
        { time: "00:15", tag: "tip", title: "查看是否出团：chameleonstargazing.com/weather",
          notes: ["确认函：当天会提前 30 分钟在该网址公布是否出团"] },
        { time: "00:50", tag: "p0", title: "抵达集合点（报道 00:45 / 开始 01:00）", addr: "70 Andrew Don Drive, Lake Tekapo, Canterbury 7999", tel: "+64 27 365 7091",
          notes: ["必须使用 Google Maps，其他地图可能带错路", "不要白天来踩点，白天容易迷路，晚上才有路牌",
                  "只需开团前 5–10 分钟到，早到车灯会严重影响上一团客人 → 00:50 到即可，别 00:20 就去等",
                  "2 批各 4 人（乔治家中文团）", "南极光需 KP≥5 + 晴天 + 低月光，真实概率约 30–40%"] },
        { time: "02:30", tag: "tip", title: "观星结束 → 回民宿补觉",
          notes: ["2–2.5h，回程也就 5–15min，抓紧睡"] },
        { time: "10:30", tag: "tip", title: "退房",
          notes: ["早餐民宿简单解决", "若 9/29 没买到三文鱼，今天走 SH8 直达不经过瓦纳卡，补买机会基本没有——昨天是最后窗口"] },
        { time: "11:00", tag: "drive", title: "出发：SH8 经 Lindis Pass 直达皇后镇（260km / 约 3h）",
          notes: ["不要走「经瓦纳卡」路线（加停靠共 5–5.5h），16:00 的 Skyline 必误", "出发前在 Twizel / Omarama 加满油，今天是最长的转场日", "Lindis Pass 是高原路段，春季可能有雪／结冰，出发前查路况"] },
        { time: "14:15", tag: "stay", title: "抵达民宿 · 入住", addr: "5 Saint Marks Lane, Queenstown 9300",
          notes: ["客厅看湖", "有 3 间是两张单人床（提前分房）"] },
        { time: "15:15", tag: "p0", title: "已订 · Skyline Gondola + Luge 5 圈（8 人）", addr: "Skyline Queenstown, 53 Brecon Street", tel: "+64 3 441 0101",
          notes: ["确认函是 Open Time（无固定场次），现场凭确认函取票", "缆车只能往返一次；Luge 必须在营业时间内用完（9/30–11/25 时段为 10:00–19:00），缆车本身开到 21:00",
                  "推荐动线：缆车上山 → 观景平台拍照 → Luge 5 圈 → 山顶餐厅/咖啡 → 短步道拍照 → 缆车下山（1.5–2h）", "先观景拍照再玩 Luge；日落前后人多，要给排队留时间"] },
        { time: "18:30", tag: "meal", title: "晚餐 · Madam Woo 或 Winnie's",
          notes: ["Madam Woo：东南亚菜，营业到 22:00", "Winnie's Gourmet Pizza Bar：披萨，营业到凌晨 2:30（转场日累，想早点吃就选这家）"] },
      ],
    },
    {
      id: 9, iso: "2026-10-02", date: "10/2", weekday: "周五",
      title: "瓦纳卡日 · 孤独的树 + 皮划艇 + 射击", stay: "皇后镇",
      items: [
        { time: "08:30", tag: "drive", title: "出发去瓦纳卡（70km / 1.3h，Crown Range 盘山路）",
          notes: ["遇雪／结冰必须查路况，必要时改走 Cromwell（SH6，约 105km / 1.5h）",
                  "餐食备选：Tarras Country Cafe（SH6 路边，营业到 15:00）、High Country Salmon（Twizel 南 3km）——这两家今天不顺路，只在改线时参考"] },
        { time: "09:10", tag: "p1", title: "Cardrona Hotel 短停（0.5h）",
          notes: ["从瓦纳卡去皇后镇的经典顺路点，拍照为主", "免费；餐饮 NZD 20–60"] },
        { time: "10:10", tag: "p1", title: "That Wanaka Tree 孤独的树（0.5–1h）",
          notes: ["免费、代表性强", "不要靠近或攀爬树（已被人为破坏过）", "不做过多停留"] },
        { time: "10:45", tag: "p1", title: "瓦纳卡湖皮划艇 / SUP（1.5–2.5h）",
          notes: ["湖水仅 10–12℃：建议光脚或拖鞋（会踩水）、坐垫处裤子会湿、禁棉质禁牛仔、人字拖会脱落",
                  "带整套干衣 + 干袋 + 防水袋", "风大不建议下水；现场买票"] },
        { time: "12:15", tag: "meal", title: "午餐 · 简餐或打包",
          notes: ["冲突点：13:30 要签到射击，正餐来不及", "把 GUSTO 或 Francesca's 的正餐挪到射击后 15:45"] },
        { time: "13:15", tag: "p0", title: "抵达 Crossfire Shooting", addr: "9 Mt Barker Road, Wanaka（SH6 与 Mt Barker Road 路口，瓦纳卡机场对面）", tel: "(03) 443 5995",
          notes: ["确认函是 Crossfire Shooting，不是表里的 Real Guns Wanaka", "电子票直接出示，无需打印"] },
        { time: "13:30", tag: "p0", title: "签到 → 13:45 开始 · 射击（6 人，1 队不参与）",
          notes: ["确认函：请提前 15 分钟抵达和签到", "现场务必确认套餐是否含 .50 BMG 巴雷特（确认函只写「超值射击体验套餐」，未列明枪型）", "避免低领衣（弹壳会烫）"] },
        { time: "15:15", tag: "p1", title: "射击结束",
          notes: ["不参与者：Bike Lounge 是唯一按小时租车的店，所有店 17:00 关门；有助力车（带电池），不熟骑车要注意"] },
        { time: "15:45", tag: "meal", title: "正餐 · GUSTO（中餐）或 Francesca's（意大利）",
          notes: ["射击后的正式午餐", "也可顺路看 Wānaka Sequoia 巨树、Wanaka Hill Park Lookout（湖边步行 1h）"] },
        { time: "17:00", tag: "drive", title: "启程回皇后镇（1.3h）",
          notes: ["别拖到天黑走 Crown Range 山路（日落约 19:50）", "骑行／玩水后疲劳驾驶风险高"] },
        { time: "18:30", tag: "meal", title: "晚餐 · 皇后镇简餐",
          notes: ["Balls and Bangles / The Exchange（人均 25–45）；或 Madam Woo / Winnie's / Flame Bar & Grill / Blue Kanu",
                  "Madam Woo 提前 2 小时取消免费", "今晚顺手把 10/3 的菜买好（明天晚餐「自己家里做」）"] },
      ],
    },
    {
      id: 10, iso: "2026-10-03", date: "10/3", weekday: "周六",
      title: "米尔福德峡湾 Fly-Cruise-Fly", stay: "皇后镇",
      items: [
        { time: "08:30", tag: "call", title: "天气确认 +64 3 249 6000 / 0800 65 65 01", tel: "+64 3 249 6000",
          notes: ["确认函：天气确认时间 08:30", "没确认别贸然出发"] },
        { time: "09:05", tag: "p0", title: "抵达接送点 · The Rees Hotel 对面的公交车站", addr: "The Rees Hotel, 377 Frankton Road, Queenstown", tel: "0800 65 65 01",
          notes: ["最容易被搞错的一条：不是自己去机场，是到公交站等班车", "确认函：接送时间 09:15 起，请在接送时间前 5–10 分钟到达并等候班车",
                  "从 5 Saint Marks Lane 出发约 5–8 分钟车程，09:00 出门", "自驾集合备选地址：39 Lucas Place, Frankton（仅在不需接送时用）", "迟到不退"] },
        { time: "10:00", tag: "p0", title: "出发 · 飞机 + 游船 + 飞机（8 人）",
          notes: ["飞行约 35–45min/段，全程 4–5h", "返程免费送回原接送点"] },
        { time: "15:00", tag: "tip", title: "返回皇后镇",
          notes: ["飞行延误是常态，下午别钉死任何不可退的项目"] },
        { time: "16:00", tag: "p1", title: "机动时段",
          notes: ["若还有精力：Glenorchy 自驾（皇后镇 45min）—— 租车合同把 Glenorchy–Paradise Road 列为保险除外责任，只能开到 Glenorchy 镇／码头，不能进 Paradise", "或回民宿休息"] },
        { time: "18:30", tag: "meal", title: "晚餐 · 自己家里做",
          notes: ["菜要 10/2 晚上买好", "今天是周六，超市和餐厅人都多", "峡湾沙蝇凶，DEET 防蚊喷雾记得带（1 队、4 队物品清单「未完成」）"] },
      ],
    },
    {
      id: 11, iso: "2026-10-04", date: "10/4", weekday: "周日",
      title: "滑翔伞 + Shotover Jet + Ddrive 自驾快艇", stay: "皇后镇",
      items: [
        { time: "09:30", tag: "tip", title: "查天气 nzgforce.com/flight-status",
          notes: ["确认函：买缆车票前务必查天气，天气允许才买票上山", "天气取消可退款"] },
        { time: "10:15", tag: "p0", title: "抵达 Skyline 山脚，自行买缆车票上山", addr: "Skyline Queenstown, 53 Brecon Street", tel: "0800 759 688",
          notes: ["确认函：请至少提前 45 分钟抵达山脚购买缆车票前往山顶集合（11:00 场次 → 10:15 到）", "上山后找 G-Force 柜台（Stratosfare Restaurant 门口）",
                  "落地后若还要再坐缆车上山，务必让 Gforce 在手腕盖章，否则要重新买票",
                  "附件里只有 OUXIAO 2 人、11:00 场这一份确认单；表里还写「2+3 队 9:15 到缆车 / 10:00 开始」——出发前必须找到那一份确认函核对"] },
        { time: "11:00", tag: "p0", title: "滑翔伞开始（约 1–1.5h）",
          notes: ["教练拍照/视频通常额外收费，预订时确认影像包价格", "4 队皇后镇 citywalk（不参与）"] },
        { time: "12:30", tag: "meal", title: "午餐 · 打包 / 车上吃",
          notes: ["今天中午最紧：12:30 结束 → 13:15 必须出发去 Shotover，只剩 45 分钟", "Vudu Cafe / Bespoke Kitchen（人均 25–40）建议打包带走，别坐下来吃"] },
        { time: "13:15", tag: "drive", title: "出发 → Shotover Jet（市区约 15–20min）", addr: "Shotover Jet Beach, 3 Arthurs Point Road, Arthurs Point", tel: "+64 3 442 8570", notes: [] },
        { time: "13:45", tag: "p0", title: "签到 → 14:15 开始 · 喷射快艇（8 人）",
          notes: ["确认函：请在行程时间前 30 分钟在基地办理登记", "1.5–2h", "会湿会冷，钥匙手机钱包全部寄存或进防水袋；怕晕怕水者谨慎", "迟到不退"] },
        { time: "16:00", tag: "drive", title: "前往 Ddrive（市区约 15–20min）", addr: "88 Beach Street, CBD, Queenstown 9300", tel: "+64 27 299 5558", notes: [] },
        { time: "16:45", tag: "p0", title: "签到 → 17:00 开始 · Ddrive 自驾快艇（4 人）",
          notes: ["确认函：提前 15 分钟签到；受天气影响，请提前致电 +64 27 299 5558 确认", "4 位驾驶员，1 小时快艇时长（男生体验，女生拍照）", "2–3h"] },
        { time: "16:30", tag: "p1", title: "其余 4 人 · 自由活动",
          notes: ["回民宿洗澡 → 湖边 → Fergburger → 伴手礼", "19:00 汇合晚餐"] },
        { time: "19:30", tag: "meal", title: "FINE DINNER · Flame Bar & Grill（必订）",
          notes: ["Flame Bar & Grill：牛排·肋排，人均 45–70，必订", "Blue Kanu：太平洋融合，人均 45–70", "Winnie's：披萨酒吧，人均 30–50"] },
      ],
    },
    {
      id: 12, iso: "2026-10-05", date: "10/5", weekday: "周一",
      title: "跳伞 → 转场奥马鲁 → 维多利亚街区 → 小蓝企鹅", stay: "奥马鲁",
      items: [
        { time: "07:45", tag: "call", title: "等 NZone 短信（跳伞前 30 分钟发）", tel: "+64 3 442 5867",
          notes: ["确认函：跳伞前 30 分钟会发短信确认天气和出发时间", "若出发不到 25 分钟前没收到，致电 +64 3 442 5867 / 0800 376 796"] },
        { time: "08:00", tag: "p0", title: "抵达 NZONE Shop", addr: "35 Shotover Street, Queenstown", notes: [] },
        { time: "08:15", tag: "p0", title: "签到 → 08:30 开始 · 15000ft 高空跳伞（1 人）",
          notes: ["预计 12:00 才结束（含往返机场、装备、视频），3–4h", "照片/视频另计（摄影约 NZ$249）", "迟到不退"] },
        { time: "08:30", tag: "p1", title: "其余 7 人 · 上午自由活动",
          notes: ["早餐 / citywalk / Fergburger / 湖边", "不要提前出发——表里「09:00 离开皇后镇」已作废"] },
        { time: "12:15", tag: "meal", title: "午餐 · 皇后镇",
          notes: ["Balls and Bangles / The Exchange（人均 25–45），湖边一圈都是"] },
        { time: "12:30", tag: "drive", title: "统一发车去奥马鲁（300km / 3.5–4h）",
          notes: ["兜底原则：企鹅不可退、跳伞可改期", "若跳伞因天气顺延超过 12:30，宁可放弃跳伞也要保 19:30 的企鹅", "中途 Timaru / Ashburton 可找咖啡馆歇脚"] },
        { time: "16:45", tag: "stay", title: "抵达民宿 · 入住", addr: "62A Reed Street, Oamaru 9400",
          notes: ["华人房东，能停两辆车"] },
        { time: "17:30", tag: "p1", title: "Victorian Precinct 维多利亚街区",
          notes: ["1–2h，免费，白石建筑和复古街区", "店铺关门较早，先逛街区再去企鹅"] },
        { time: "18:45", tag: "meal", title: "晚餐",
          notes: ["企鹅 20:00 才开始，要看营业时间长的：Domino's Pizza Oamaru（22:00 关门）、麦当劳（22:00 关门）", "或者早点到奥马鲁先吃——早点吃选择很多"] },
        { time: "19:30", tag: "p0", title: "签到 → 20:00 开始 · 小蓝企鹅归巢（8 人）", addr: "Oamaru Blue Penguin Colony, Waterfront Road, Oamaru 9400", tel: "+64 (0)3 4331195",
          notes: ["确认函：门口有免费停车位，请至少提前 30 分钟抵达签到；迟到不退", "海边风大，注意保暖（夜间 5–8℃，体感更低）", "禁止闪光灯；手机屏幕调到最暗、不要开手电——企鹅对光极敏感", "1.5–2h"] },
        { time: "21:30", tag: "tip", title: "回民宿 · 收拾行李",
          notes: ["明天 10/6 返基督城，今晚把东西收好"] },
      ],
    },
    {
      id: 13, iso: "2026-10-06", date: "10/6", weekday: "周二",
      title: "奥马鲁 → 基督城 · 伴手礼采购 + 车辆收尾", stay: "基督城",
      items: [
        { time: "09:00", tag: "drive", title: "出发返基督城（250km / 3–3.5h）",
          notes: ["早餐民宿简单解决"] },
        { time: "12:00", tag: "meal", title: "午餐 · Timaru / Ashburton 咖啡馆，或到基督城 Riverside Market",
          notes: ["Riverside Market 是市中心市集，选择很多"] },
        { time: "14:30", tag: "stay", title: "抵达民宿 · 入住", addr: "25 Teesdale Street, Burnside, Christchurch 8053",
          notes: ["离机场近（约 10min），方便明早还车"] },
        { time: "15:00", tag: "p1", title: "伴手礼采购 / 超市 / 药妆",
          notes: ["食品、蜂蜜、液体和药品按航空/海关规则整理——蜂蜜和液体必须托运", "20:00 前必须结束采购"] },
        { time: "20:00", tag: "alert", title: "车辆收尾（2 台都要）",
          notes: ["① 加满油（留好小票）", "② 清理车内垃圾和个人物品", "③ 确认机场还车点位置与自助还车流程", "④ 拍油表 + 里程 + 车身四周照片（防事后争议）"] },
        { time: "21:00", tag: "tip", title: "线上值机 + 行李称重",
          notes: ["墨尔本中转不出机场，但澳洲过境签要再核一次"] },
        { time: "22:30", tag: "tip", title: "睡",
          notes: ["晚餐备选：King of Snake（欧亚融合，人均 45–70，12:00–24:00）、Zodiac（中餐 40–60）、5th Street（45–65）、Downstairs（酒吧餐 40–60）"] },
      ],
    },
    {
      id: 14, iso: "2026-10-07", date: "10/7", weekday: "周三",
      title: "06:20 基督城 → 墨尔本 → 17:55 香港 · 返程", stay: "返程",
      items: [
        { time: "03:00", tag: "alert", title: "起床", notes: [] },
        { time: "03:30", tag: "drive", title: "出发去机场",
          notes: ["民宿 → CHC 约 10min，还车预留 20 分钟"] },
        { time: "04:00", tag: "flight", title: "还车 + 值机 + 安检",
          notes: ["国际航班提前 2–2.5h，06:20 的飞机 04:00 到是安全的"] },
        { time: "06:20", tag: "flight", title: "QF168 CHC 起飞 → 墨尔本 T2（08:10）→ QF029（11:15）→ 17:55 抵达香港",
          notes: ["中转 3 小时 5 分钟，行李直挂、中转不用取行李", "澳洲过境签再核一次"] },
      ],
    },
  ],

  /* 关键电话与地址速查 */
  contacts: [
    { name: "凯库拉观鲸（3人/5人）", addr: "Air Kaikoura Aero Club, 627 SH1, Peketa, Kaikōura 7374", tel: "+64 3 319 6579", report: "08:30 / 09:30", note: "不是 Kaikoura Airport，更不是码头；出发前 1 小时务必致电确认天气" },
    { name: "库克山 Heli-Hike", addr: "Mt Cook Airport, Mount Cook Road 7999", tel: "0800 650 651", report: "10:45", note: "早上致电确认飞行状态" },
    { name: "观星（乔治家）", addr: "70 Andrew Don Drive, Lake Tekapo 7999", tel: "+64 27 365 7091", report: "00:45", note: "必须用 Google Maps；早到会干扰上一团" },
    { name: "Skyline 缆车 + Luge", addr: "53 Brecon Street, Queenstown", tel: "+64 3 441 0101", report: "Open Time", note: "缆车 9:30–21:00；Luge 10:00–19:00" },
    { name: "瓦纳卡射击 Crossfire", addr: "9 Mt Barker Road, Wanaka（机场对面）", tel: "(03) 443 5995", report: "13:30", note: "不是表里的 Real Guns；务必确认是否含 .50 BMG" },
    { name: "米尔福德接送", addr: "The Rees Hotel 对面公交站, 377 Frankton Road", tel: "0800 65 65 01", report: "接送 09:15", note: "不是机场；08:30 先确认天气（+64 3 249 6000）" },
    { name: "滑翔伞 GFORCE", addr: "Skyline 山顶（Stratosfare Restaurant 门口柜台）", tel: "0800 759 688", report: "提前 45min 到山脚", note: "先查 nzgforce.com/flight-status 再买缆车票" },
    { name: "Shotover Jet", addr: "3 Arthurs Point Road, Arthurs Point", tel: "+64 3 442 8570", report: "13:45", note: "提前 30 分钟登记" },
    { name: "Ddrive 自驾快艇", addr: "88 Beach Street, CBD, Queenstown 9300", tel: "+64 27 299 5558", report: "16:45", note: "受天气影响，提前致电确认" },
    { name: "NZone 跳伞", addr: "35 Shotover Street, Queenstown", tel: "+64 3 442 5867", report: "08:15", note: "0800 376 796；约 12:00 才结束" },
    { name: "小蓝企鹅", addr: "Waterfront Road, Oamaru 9400", tel: "+64 (0)3 4331195", report: "19:30", note: "门口免费停车；禁闪光灯" },
    { name: "蒂卡波民宿", addr: "48 Darchiac Drive, Lake Tekapo 7999", tel: "03 6806952", report: "15:00–17:00", note: "17:00 后须致电安排自助入住" },
  ],

  /* 住宿 */
  stays: [
    { city: "基督城（到达）", dates: "9/25–9/28（3晚）", addr: "198 Chester Street East, Christchurch Central City 8011", tel: "", cancel: "9/20 已过",
      notes: ["实际两套公寓", "行李搬上二楼", "马路停车位"] },
    { city: "蒂卡波湖", dates: "9/28–10/1（3晚）", addr: "48 Darchiac Drive, Lake Tekapo 7999", tel: "03 6806952", cancel: "9/27（剩 4 天）",
      notes: ["前台 15:00–17:00；17:00 后须致电 03 6806952", "客人免费 9 洞高尔夫 + 宠物动物园", "Four Square 8:00–20:00"] },
    { city: "皇后镇", dates: "10/1–10/5（4晚）", addr: "5 Saint Marks Lane, Queenstown 9300", tel: "", cancel: "9/1 已过",
      notes: ["客厅看湖", "有 3 间是两张单人床", "有壁炉"] },
    { city: "奥马鲁", dates: "10/5–10/6（1晚）", addr: "62A Reed Street, Oamaru 9400", tel: "", cancel: "9/30（剩 7 天）",
      notes: ["华人房东", "能停两辆车"] },
    { city: "基督城（离开）", dates: "10/6–10/7（1晚）", addr: "25 Teesdale Street, Burnside, Christchurch 8053", tel: "", cancel: "10/1（剩 8 天）",
      notes: ["离机场近（约 10min）"] },
  ],
  cancelNote: "皇后镇 ¥20,857（9/1）与基督城到达 ¥11,161（9/20）已过期，共 ¥31,000 锁死。仍可动：库克山 Heli-Hike 9/24 → 蒂卡波 ¥15,353（9/27）→ 奥马鲁 ¥2,578（9/30）→ 基督城离开 ¥2,215（10/1）。",

  /* 餐食速查 */
  meals: [
    { date: "9/25", plan: "晚餐 Fiddlesticks Restaurant 19:15（预订名 Robert）", point: "餐后 PAK'nSAVE Moorhouse 采购（22:00 关门）" },
    { date: "9/26", plan: "早 Farmers' Market（周六 9–12）／午 Little High Eatery 或 Riverside Market／晚 回家做", point: "United Fisheries 早上卖鳌虾；今晚做 9/27 便当" },
    { date: "9/27", plan: "早 不吃或便当（清淡）／午 Kaikoura Seafood BBQ Kiosk／晚 美食广场或回家做", point: "周日晚上多数餐厅歇业" },
    { date: "9/28", plan: "午 Fairlie Bakehouse（鹿肉蔓越莓派）／晚 TLV Restaurant & Bar 20:15", point: "派可提前 2 天订（9/26 前）；不可订座" },
    { date: "9/29", plan: "午 The Old Mountaineers Cafe／晚 自己做或镇上", point: "三文鱼店 17:00 关门" },
    { date: "9/30", plan: "早 民宿／午 Mackenzies（walk-in）／晚 自己做", point: "Blue Lake Eatery 已停业；保底 Mackenzies 19:15" },
    { date: "10/1", plan: "早 民宿／晚 Madam Woo（22:00 关）或 Winnie's（凌晨 2:30 关）", point: "转场日，选营业晚的" },
    { date: "10/2", plan: "午 简餐（正餐挪到 15:45 GUSTO / Francesca's）／晚 皇后镇简餐", point: "人均 25–45；今晚买好 10/3 的菜" },
    { date: "10/3", plan: "晚餐自己家里做", point: "菜要 10/2 晚上买好" },
    { date: "10/4", plan: "午 Vudu Cafe / Bespoke Kitchen（打包）／晚 Flame Bar & Grill（必订）", point: "中午时间最紧" },
    { date: "10/5", plan: "午 皇后镇／晚 奥马鲁（Domino's、麦当劳均 22:00 关）", point: "企鹅 20:00 才开始；早点到奥马鲁选择更多" },
    { date: "10/6", plan: "午 Timaru/Ashburton 咖啡馆或 Riverside Market／晚 King of Snake、Zodiac、5th Street", point: "20:00 前结束采购" },
  ],

  /* 自驾与租车 */
  driving: {
    rows: [
      { k: "车辆", v: "三菱帕杰罗运动版或同组 × 2（自动挡 / 4 门 / 7 座 / 四驱）" },
      { k: "提车单号", v: "Rental Voucher 1008979697 与 1008979737（车辆1.pdf / 车辆2.pdf）" },
      { k: "取车必备", v: "中国驾照原件 + 官方翻译件、芯片国际信用卡（主驾驶人名下）、提车单、护照" },
      { k: "副驾驶人", v: "默认只有一个主驾驶人，提车时必须登记副驾驶人并额外付费——不登记的人开车出事全责自付" },
      { k: "押金", v: "每车 NZ$200–500 预授权，信用卡额度要够" },
      { k: "导航", v: "探途地图 tantu.com；观星集合点必须用 Google Maps" },
      { k: "加油", v: "Gaspy 查油价；库克山无加油站，蒂卡波/Twizel 加满；Lindis Pass 段中途补给点少" },
      { k: "停车", v: "ParkMate / PayMyPark 缴费；每车备 NZ$20 硬币应付无人值守停车场" },
    ],
    forbidden: [
      "Skippers Canyon Road（含海滩）", "90 Mile Beach", "Coromandel Colville 以北", "Tapu–Coroglen 路",
      "库克山 Ball Hut Road", "Glenorchy–Paradise Road", "皇后镇 Deer Park Heights", "所有非商业滑雪场道路", "一切未铺装／封闭道路",
    ],
    forbiddenNote: "开进去不违法，但属于保险除外责任——一旦出事故，车损险和第三者险全部失效，维修、拖车、第三方索赔全部自付（南岛碎石路拖车费动辄 NZ$1,000 起）。落到本行程：Glenorchy 开到镇上／码头是安全的，再往 Paradise 就是裸奔；Deer Park Heights 建议不去；米尔福德陆路备选走 Milford Road 是正常公路，但往返 12–13h，只有飞行取消才考虑。",
  },

  /* 七个冲突与修正 */
  conflicts: [
    { n: 1, title: "10/3 米尔福德：集合点是公交站，不是机场",
      points: ["确认函原文：请在接送时间前 5–10 分钟到达 The Rees Hotel 对面的公交车站等班车", "09:15 起接送、10:00 出发、天气确认 08:30",
        "The Rees Hotel 在 377 Frankton Road，从 5 Saint Marks Lane 出发约 5–8 分钟车程，09:05 前必须到位",
        "自驾集合备选地址：39 Lucas Place, Frankton（只在不需要接送时用）", "08:30 先打 +64 3 249 6000 / 0800 65 65 01 确认天气，别没确认就出发", "返程免费送回原接送点",
        "当天晚餐 B 列写「计划有变！自己家里做」——建议 10/2 晚上先把菜买好"] },
    { n: 2, title: "9/27 观鲸：地址是 Peketa，且是飞机不是船",
      points: ["签到地址：Air Kaikoura Aero Club, 627 State Highway 1, Peketa, Kaikōura 7374（+64 3 319 6579）",
        "表里写的「出海固定翼」是早期文案，实际是 30 分钟固定翼飞行", "3 人班 09:00 起飞 / 08:30 前签到；5 人班 10:00 起飞 / 09:30 签到",
        "出发前 1 小时务必致电确认天气与最小成行人数——这条写在确认函里", "该带晕机药（4 队物品清单「未完成」）；当天早餐不吃或清淡",
        "机舱窄，只带小腰包 + 相机 + 墨镜", "低空绕鲸盘旋倾斜转弯很晃", "迟到按 NO SHOW，不退不改"] },
    { n: 3, title: "10/1 三连压缩：凌晨观星 → 10:30 退房 → 260km 转场 → Skyline",
      points: ["观星：70 Andrew Don Drive, Lake Tekapo，00:45 报道 / 01:00 开始（2 批各 4 人）",
        "确认函特别强调：只需开团前 5–10 分钟到，早到车灯会严重影响上一团客人 → 00:50 到即可",
        "必须用 Google Maps（其他地图会带错路），白天不要去踩点", "当天提前 30 分钟在 chameleonstargazing.com/weather 公布是否出团",
        "转场：走 SH8 经 Lindis Pass 直达，260km / 3h。若改走「经瓦纳卡」要 5–5.5h，16:00 的 Skyline 必误",
        "Skyline 是 Open Time：缆车 9:30–21:00、Luge 10:00–19:00。14:30 到 → 15:00 上山，时间从容"] },
    { n: 4, title: "10/5 跳伞与奥马鲁转场：表里「09:00 离开皇后镇」已作废",
      points: ["NZone 确认函：35 Shotover Street，08:15 签到 / 08:30 开始，预计 12:00 结束",
        "跳伞前 30 分钟会发短信确认天气和出发时间；若 25 分钟前没收到，打 +64 3 442 5867 / 0800 376 796",
        "修正：12:30 统一发车 → 奥马鲁 300km / 3.5–4h → 16:30–17:00 到 → 17:30 维多利亚街区 → 19:30 签到 / 20:00 企鹅",
        "兜底原则：企鹅不可退、跳伞可改期，跳伞顺延就放弃跳伞保企鹅", "其余 7 人上午自由活动，不要提前出发"] },
    { n: 5, title: "9/29 库克山：Heli-Hike 与三文鱼店 17:00 关门",
      points: ["Heli-Hike 10:45 签到 / 11:00 开始（Mt Cook Airport, Mount Cook Road），3–4h → 约 15:00 结束",
        "三文鱼超市 17:00 关门，需要 16:00 结束库克山才能买到", "Mt Cook Alpine Salmon Shop 在普卡基湖畔 SH80 路口，回程顺路，库克山过来约 40–50min",
        "结论：Heli-Hike 后直接回程，Hooker Valley 步道（2–3h）只能作为直升机取消时的替代",
        "早上出发前打 0800 650 651 确认飞行状态", "库克山无加油站，蒂卡波/Twizel 必须加满油", "装备由对方提供（鞋、外套、冰爪、袜、杖、包、墨镜）"] },
    { n: 6, title: "10/2 瓦纳卡：皮划艇 + 正餐 + 射击，三者塞不进一个中午",
      points: ["确认函是 Crossfire Shooting（不是 Real Guns），地址 9 Mt Barker Road, Wanaka（瓦纳卡机场对面），13:45 开始 / 13:30 签到，6 人",
        "时间账：09:00 皇后镇出发 → 10:10 孤独的树 → 10:45 皮划艇（1.5h）→ 12:15 上岸 → 13:30 签到，中间只剩 1 小时 15 分",
        "修正：中午只做简餐/打包，把 GUSTO／Francesca's 正餐挪到 15:45 射击结束后", "现场务必确认套餐是否含 .50 BMG",
        "皮划艇水温 10–12℃：光脚或拖鞋、别穿棉质牛仔、坐垫处裤子会湿、带整套干衣 + 干袋；风大不下水",
        "不玩射击的人：Bike Lounge 是唯一按小时租车的店，所有店 17:00 关门", "17:00 前必须启程回皇后镇，别天黑走 Crown Range 山路"] },
    { n: 7, title: "10/4 滑翔伞确认函只有一份，且中午最紧",
      points: ["附件里只有 OUXIAO × 2 人、10/4 11:00 场次的 GFORCE 确认单；表里还写着「2+3 队 9:15 到缆车 / 10:00 开始」——那份确认函没在附件里，出发前必须找到并核对",
        "硬要求：提前 45 分钟到 Skyline 山脚（53 Brecon Street）自行买缆车票上山 → 11:00 场次 10:15 到山脚", "上山后找 G-Force 柜台（Stratosfare Restaurant 门口）",
        "买票前先查 nzgforce.com/flight-status，天气取消可退款", "落地后若还要再坐缆车上山，务必让 Gforce 在手腕盖章，否则要重新买票",
        "时间账：11:00 起飞 → 约 12:30 结束 → 12:45 回市区 → 午餐只有 30 分钟 → 13:15 出发 → 13:45 Shotover 签到"] },
  ],

  /* 出发前 24 小时清单（可勾选） */
  checklist: [
    { group: "证件 · 全员必带", items: [
      "全队完成 NZTD 入境申报（1、2、4 队仍是「未完成」）——登机前 24 小时内才能提交",
      "打印：签证 / 行程单 / 保险复印件（3 队未完成）",
      "药品申报说明打印（2、3、4 队未完成）",
      "驾照原件 + 官方翻译件（2、3 队还是「已准备」未「已打包」）——没翻译件提不了车",
      "澳洲过境签 771 批准信打印——值机必查，务必带纸质件",
      "所有确认函截图 + 离线 PDF 双份（南岛山区常无信号）",
    ]},
    { group: "钱 · 车", items: [
      "芯片国际信用卡在主驾驶人名下、额度够付押金（每车 NZ$200–500 预授权）",
      "提车时登记副驾驶人（默认只含 1 人）",
      "每车备 NZ$20 硬币（无人值守停车场、Mt John 道路费等）",
    ]},
    { group: "物品补齐", items: [
      "晕机药（4 队未完成，9/27 观鲸必用）",
      "防蚊喷雾 DEET（1、4 队未完成，峡湾沙蝇）",
      "拖鞋 / 充电宝（3、4 队）",
    ]},
    { group: "App 下载", items: [
      "Gaspy（油价）",
      "ParkMate / PayMyPark（停车缴费）",
      "MetService（官方天气）",
      "Google Maps（观星导航强制）",
    ]},
    { group: "入境生物安全（容易被罚）", items: [
      "所有户外鞋 / 登山杖 / 帐篷上的泥土必须清理干净",
      "含伪麻黄碱的感冒药必须申报（不申报最高罚 NZ$400）",
      "食品、蜂蜜、植物制品一律申报，宁可多报",
    ]},
  ],
};
